import { Milestone, Donation, Expense, NGO, FraudAlert, TransparencyStats } from './types';

export const mockNGOs: NGO[] = [
  {
    id: '1',
    name: 'Clean Water Initiative',
    walletAddress: '0x1234...5678',
    description: 'Providing clean drinking water to rural communities across Africa through sustainable well construction and water purification systems.',
    category: 'Water & Sanitation',
    verified: true,
    totalReceived: '125.5',
    totalMilestones: 12,
    completedMilestones: 8,
    rating: 4.8,
    createdAt: new Date('2024-01-15'),
    image: 'https://images.unsplash.com/photo-1594398901394-4e34939a4fd0?w=400&h=300&fit=crop',
    location: 'Kenya, Africa',
    donorCount: 234,
  },
  {
    id: '2',
    name: 'Education For All',
    walletAddress: '0x8765...4321',
    description: 'Building schools and providing educational resources in underserved areas to empower the next generation.',
    category: 'Education',
    verified: true,
    totalReceived: '89.2',
    totalMilestones: 8,
    completedMilestones: 6,
    rating: 4.6,
    createdAt: new Date('2024-02-20'),
    image: 'https://images.unsplash.com/photo-1497486751825-1233686d5d80?w=400&h=300&fit=crop',
    location: 'India',
    donorCount: 189,
  },
  {
    id: '3',
    name: 'Green Earth Foundation',
    walletAddress: '0xABCD...EFGH',
    description: 'Environmental conservation and reforestation projects worldwide, planting trees and protecting endangered ecosystems.',
    category: 'Environment',
    verified: true,
    totalReceived: '203.8',
    totalMilestones: 15,
    completedMilestones: 12,
    rating: 4.9,
    createdAt: new Date('2023-11-05'),
    image: 'https://images.unsplash.com/photo-1542601906990-b4d3fb778b09?w=400&h=300&fit=crop',
    location: 'Global',
    donorCount: 567,
  },
  {
    id: '4',
    name: 'Healthcare Heroes',
    walletAddress: '0xDEF1...2345',
    description: 'Providing essential healthcare services and medical supplies to remote communities lacking access to hospitals.',
    category: 'Healthcare',
    verified: true,
    totalReceived: '156.3',
    totalMilestones: 10,
    completedMilestones: 7,
    rating: 4.7,
    createdAt: new Date('2024-03-01'),
    image: 'https://images.unsplash.com/photo-1584820927498-cfe5211fd8bf?w=400&h=300&fit=crop',
    location: 'Bangladesh',
    donorCount: 312,
  },
  {
    id: '5',
    name: 'Ocean Guardians',
    walletAddress: '0x9876...WXYZ',
    description: 'Protecting marine ecosystems through ocean cleanup initiatives and coral reef restoration projects worldwide.',
    category: 'Environment',
    verified: true,
    totalReceived: '78.9',
    totalMilestones: 6,
    completedMilestones: 4,
    rating: 4.5,
    createdAt: new Date('2024-01-28'),
    image: 'https://images.unsplash.com/photo-1583212292454-1fe6229603b7?w=400&h=300&fit=crop',
    location: 'Indonesia',
    donorCount: 145,
  },
  {
    id: '6',
    name: 'Rural Tech Connect',
    walletAddress: '0xFEDC...BA98',
    description: 'Bridging the digital divide by providing technology education and internet access to rural communities.',
    category: 'Education',
    verified: true,
    totalReceived: '45.6',
    totalMilestones: 5,
    completedMilestones: 3,
    rating: 4.4,
    createdAt: new Date('2024-04-10'),
    image: 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=400&h=300&fit=crop',
    location: 'Philippines',
    donorCount: 98,
  },
  {
    id: '7',
    name: 'Hunger Relief Network',
    walletAddress: '0x1357...2468',
    description: 'Fighting hunger through food distribution programs, community gardens, and sustainable agriculture training.',
    category: 'Healthcare',
    verified: false,
    totalReceived: '67.2',
    totalMilestones: 8,
    completedMilestones: 5,
    rating: 4.3,
    createdAt: new Date('2024-02-15'),
    image: 'https://images.unsplash.com/photo-1488521787991-ed7bbaae773c?w=400&h=300&fit=crop',
    location: 'Ethiopia',
    donorCount: 203,
  },
  {
    id: '8',
    name: 'Safe Shelter Project',
    walletAddress: '0x2468...1357',
    description: 'Building sustainable housing solutions for displaced families and disaster-affected communities.',
    category: 'Water & Sanitation',
    verified: true,
    totalReceived: '134.7',
    totalMilestones: 11,
    completedMilestones: 9,
    rating: 4.8,
    createdAt: new Date('2023-12-20'),
    image: 'https://images.unsplash.com/photo-1460317442991-0ec209397118?w=400&h=300&fit=crop',
    location: 'Nepal',
    donorCount: 421,
  },
];

export const mockMilestones: Milestone[] = [
  {
    id: 'm1',
    title: 'Well Construction Phase 1',
    description: 'Dig and install 5 water wells in Kibera region',
    targetAmount: '15.0',
    currentAmount: '15.0',
    status: 'approved',
    deadline: new Date('2024-03-15'),
    proofHash: 'Qm...abc123',
    validatorApprovals: 3,
    requiredApprovals: 2,
    createdAt: new Date('2024-01-20'),
  },
  {
    id: 'm2',
    title: 'Water Purification Systems',
    description: 'Install purification units in 10 villages',
    targetAmount: '25.0',
    currentAmount: '18.5',
    status: 'in_progress',
    deadline: new Date('2024-04-30'),
    validatorApprovals: 0,
    requiredApprovals: 2,
    createdAt: new Date('2024-02-01'),
  },
  {
    id: 'm3',
    title: 'Community Training Program',
    description: 'Train local communities on water system maintenance',
    targetAmount: '8.0',
    currentAmount: '2.3',
    status: 'pending',
    deadline: new Date('2024-05-15'),
    validatorApprovals: 0,
    requiredApprovals: 2,
    createdAt: new Date('2024-02-15'),
  },
  {
    id: 'm4',
    title: 'School Building Foundation',
    description: 'Complete foundation work for 3 new schools',
    targetAmount: '30.0',
    currentAmount: '30.0',
    status: 'awaiting_approval',
    deadline: new Date('2024-03-01'),
    proofHash: 'Qm...def456',
    validatorApprovals: 1,
    requiredApprovals: 2,
    createdAt: new Date('2024-01-10'),
  },
];

export const mockDonations: Donation[] = [
  {
    id: 'd1',
    donorAddress: '0xDONOR...1234',
    amount: '5.0',
    milestoneId: 'm1',
    transactionHash: '0xTX...hash1',
    timestamp: new Date('2024-02-01'),
    status: 'confirmed',
  },
  {
    id: 'd2',
    donorAddress: '0xDONOR...5678',
    amount: '10.0',
    milestoneId: 'm1',
    transactionHash: '0xTX...hash2',
    timestamp: new Date('2024-02-05'),
    status: 'released',
  },
  {
    id: 'd3',
    donorAddress: '0xDONOR...1234',
    amount: '8.5',
    milestoneId: 'm2',
    transactionHash: '0xTX...hash3',
    timestamp: new Date('2024-02-10'),
    status: 'confirmed',
  },
];

export const mockExpenses: Expense[] = [
  {
    id: 'e1',
    ngoAddress: '0x1234...5678',
    milestoneId: 'm1',
    amount: '3.2',
    description: 'Equipment rental for well drilling',
    category: 'Equipment',
    proofHash: 'Qm...exp1',
    ipfsLink: 'ipfs://Qm...exp1',
    status: 'approved',
    timestamp: new Date('2024-02-15'),
  },
  {
    id: 'e2',
    ngoAddress: '0x1234...5678',
    milestoneId: 'm1',
    amount: '5.8',
    description: 'Construction materials and labor',
    category: 'Construction',
    proofHash: 'Qm...exp2',
    ipfsLink: 'ipfs://Qm...exp2',
    status: 'approved',
    timestamp: new Date('2024-02-20'),
  },
  {
    id: 'e3',
    ngoAddress: '0x1234...5678',
    milestoneId: 'm2',
    amount: '4.5',
    description: 'Purification unit purchase',
    category: 'Equipment',
    proofHash: 'Qm...exp3',
    ipfsLink: 'ipfs://Qm...exp3',
    status: 'pending',
    timestamp: new Date('2024-03-01'),
  },
];

export const mockFraudAlerts: FraudAlert[] = [
  {
    id: 'f1',
    ngoAddress: '0xSUSPECT...1234',
    type: 'suspicious_activity',
    severity: 'medium',
    description: 'Unusual withdrawal pattern detected - multiple small transactions in short timeframe',
    status: 'active',
    timestamp: new Date('2024-03-01'),
  },
  {
    id: 'f2',
    ngoAddress: '0xANOTHER...5678',
    type: 'invalid_proof',
    severity: 'high',
    description: 'IPFS proof hash does not match submitted documentation',
    status: 'resolved',
    timestamp: new Date('2024-02-25'),
  },
];

export const mockTransparencyStats: TransparencyStats = {
  totalDonations: '418.5',
  totalNGOs: 24,
  totalMilestones: 87,
  completedMilestones: 62,
  averageCompletionTime: 45,
  fraudsPrevented: 3,
};

export const chartData = {
  donations: [
    { month: 'Jan', amount: 45.2, donors: 120 },
    { month: 'Feb', amount: 62.8, donors: 185 },
    { month: 'Mar', amount: 78.5, donors: 210 },
    { month: 'Apr', amount: 55.3, donors: 165 },
    { month: 'May', amount: 89.1, donors: 245 },
    { month: 'Jun', amount: 87.6, donors: 238 },
  ],
  milestones: [
    { status: 'Completed', value: 62, color: 'hsl(142, 71%, 45%)' },
    { status: 'In Progress', value: 18, color: 'hsl(221, 83%, 53%)' },
    { status: 'Pending', value: 7, color: 'hsl(38, 92%, 50%)' },
  ],
  categories: [
    { name: 'Water & Sanitation', value: 35 },
    { name: 'Education', value: 28 },
    { name: 'Healthcare', value: 22 },
    { name: 'Environment', value: 15 },
  ],
};
